default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  

development:
  <<: *default
  username: postgres
  password: postgres
  database: winnolingo_development
  

test:
  <<: *default
  username: postgres
  password: postgres
  database: winnolingo_test

production:
  <<: *default
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  database: winnolingo_production